version: "3.9"

services:
  ollama:
    image: ollama/ollama
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "ollama serve & sleep 5 && ollama pull phi && wait",
      ]
    ports:
      - "11434:11434"
    restart: on-failure

  app:
    build: .
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    ports:
      - "8501:8501"